import type { ModelUsageView, SopDraftView } from '@orbit/api/views';
import { describe, expect, it } from 'vitest';

import { ApiRequestError } from './api-client';
import {
  describeSopDraftFailure,
  DRAFT_NOT_EXECUTABLE_NOTICE,
  numberedSteps,
  summarizeModelSpend,
  summarizeSopDraft,
} from './sop-draft-view-model';

const DRAFT: SopDraftView = {
  documentId: 'sopdoc_123',
  revisionId: 'soprev_123',
  revisionNumber: 2,
  state: 'draft',
  title: 'Service request escalation review',
  description: null,
  steps: [
    { id: 'open_portal', kind: 'navigate', summary: 'Open the service request portal' },
    { id: 'enter_password', kind: 'fill', summary: 'Provide the portal password' },
  ],
  inputs: [{ id: 'password', label: 'Password', type: 'secret', required: true }],
  assumptions: [{ id: 'a1', statement: 'Every step is read-only.', rationale: null }],
  clarificationQuestions: [
    { id: 'q1', question: 'What indicates a password-expired notice?', aboutStepId: 'open_portal' },
  ],
  risks: [{ id: 'r1', statement: 'The directory may be a separate system.', severity: 'medium' }],
  provenance: {
    kind: 'generated',
    provider: 'anthropic',
    model: 'claude-sonnet-5',
    promptVersion: 'sop-graph-generation@1',
    generatedAt: '2026-09-05T10:00:00.000Z',
  },
  executable: false,
};

describe('summarizeSopDraft', () => {
  it('describes the revision and who produced it', () => {
    const summary = summarizeSopDraft(DRAFT);

    expect(summary.title).toBe('Service request escalation review');
    expect(summary.revisionLabel).toBe('Revision 2 · draft');
    expect(summary.stepCount).toBe(2);
    expect(summary.questionCount).toBe(1);
    expect(summary.generatedBy).toBe('Generated by anthropic claude-sonnet-5');
  });

  it('says only "Generated" when provenance carries no model', () => {
    const summary = summarizeSopDraft({
      ...DRAFT,
      provenance: { ...DRAFT.provenance, provider: null, model: null },
    });

    expect(summary.generatedBy).toBe('Generated');
  });
});

describe('numberedSteps', () => {
  it('numbers from one, the way a procedure reads', () => {
    expect(numberedSteps(DRAFT).map((step) => step.position)).toEqual([1, 2]);
    expect(numberedSteps(DRAFT)[0]?.summary).toBe('Open the service request portal');
  });
});

describe('describeSopDraftFailure', () => {
  it('treats a rejected draft as its own kind, and keeps the issues', () => {
    const failure = describeSopDraftFailure(
      new ApiRequestError({
        status: 422,
        message: 'The generated SOP Graph did not pass validation.',
        code: 'VALIDATION_ERROR',
        details: [{ field: 'entryStepId', message: '[UNKNOWN_ENTRY_STEP] no such step' }],
      }),
    );

    expect(failure.kind).toBe('rejected_draft');
    expect(failure.title).toBe('The generated workflow was rejected');
    expect(failure.issues).toEqual([
      { where: 'entryStepId', message: '[UNKNOWN_ENTRY_STEP] no such step' },
    ]);
  });

  it('does not call a provider outage an invalid workflow', () => {
    // Telling someone their description produced an invalid workflow, when the
    // truth is that no model is configured, sends them to fix the wrong thing.
    const failure = describeSopDraftFailure(
      new ApiRequestError({ status: 500, message: 'The model provider failed.' }),
    );

    expect(failure.kind).toBe('not_configured');
    expect(failure.issues).toEqual([]);
  });

  it('reports a rejected request as a request problem', () => {
    const failure = describeSopDraftFailure(
      new ApiRequestError({ status: 400, message: 'The request body is not valid.' }),
    );

    expect(failure.kind).toBe('request_failed');
  });
});

describe('the draft notice', () => {
  it('says plainly that a draft cannot start browser automation', () => {
    expect(DRAFT_NOT_EXECUTABLE_NOTICE).toContain('not executable');
    expect(DRAFT_NOT_EXECUTABLE_NOTICE).toContain('cannot start browser automation');
  });
});

/**
 * The spend display.
 *
 * It is a courtesy, not a gate — the server refuses an over-budget Generate
 * whether or not this rendered — so what matters here is that it never
 * misreports the situation: that cost is always marked as an estimate, and that
 * a scope which is out of room says which one it is.
 */
describe('summarizeModelSpend', () => {
  function usage(overrides: Partial<ModelUsageView> = {}): ModelUsageView {
    return {
      global: {
        calls: 3,
        inputTokens: 9_000,
        outputTokens: 1_000,
        totalTokens: 10_000,
        estimatedCostMicroUsd: 42_000,
      },
      document: null,
      documentId: null,
      scopes: [
        {
          scope: 'global',
          label: 'the deployment-wide budget',
          limitTokens: 1_000_000,
          spentTokens: 10_000,
          remainingTokens: 990_000,
          exhausted: false,
        },
      ],
      exhausted: false,
      costIsEstimated: true,
      ...overrides,
    };
  }

  it('has nothing to say before the figures have loaded', () => {
    expect(summarizeModelSpend(null)).toBeNull();
  });

  it('reports tokens, calls, and a cost it always marks as an estimate', () => {
    const summary = summarizeModelSpend(usage());

    expect(summary?.usedLabel).toBe('10,000 tokens across 3 model calls');
    expect(summary?.costLabel).toContain('estimated');
    expect(summary?.costLabel).toContain('$0.0420');
  });

  it('says which scope ran out, so raising the right ceiling is obvious', () => {
    const summary = summarizeModelSpend(
      usage({
        exhausted: true,
        scopes: [
          {
            scope: 'document',
            label: 'this workflow’s budget',
            limitTokens: 10_000,
            spentTokens: 10_000,
            remainingTokens: 0,
            exhausted: true,
          },
        ],
      }),
    );

    expect(summary?.exhausted).toBe(true);
    expect(summary?.blockedReason).toContain('this workflow’s budget');
  });

  it('says "uncapped" rather than showing a ceiling that does not exist', () => {
    const summary = summarizeModelSpend(
      usage({
        scopes: [
          {
            scope: 'global',
            label: 'the deployment-wide budget',
            limitTokens: null,
            spentTokens: 10_000,
            remainingTokens: null,
            exhausted: false,
          },
        ],
      }),
    );

    expect(summary?.remainingLabels).toEqual(['the deployment-wide budget: uncapped']);
  });
});

describe('describeSopDraftFailure, for a budget', () => {
  it('does not tell someone their text was rejected when they ran out of budget', () => {
    const failure = describeSopDraftFailure(
      new ApiRequestError({
        status: 429,
        message: 'This would exceed the deployment-wide budget.',
      }),
    );

    expect(failure.kind).toBe('budget_exhausted');
    expect(failure.title).toContain('budget');
  });
});
